version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "helloTutorial"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hxmra6keyxuc"
s3_prefix = "helloTutorial"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
